"""
Populate the QUAM generated by wiring_murch_blue.py with initial values.
Must be run after wiring_murch_blue.py and prior to the first experiment.

System (physical wiring matches sample_config_black.py):
  - 3 fixed-frequency transmons (Q2, Q3, Q4) in a linear chain
  - 2 tunable couplers (C23 on port 1, C34 on port 2) with flux lines
  - Q2 drive: IQ mixer on ports 3/4 (Q1_DL)
  - Q3 drive: SSB modulator on port 5 (Q2_DL)
  - Q4 drive: SSB modulator on port 9 (shared with readout, time-multiplexed)
  - Multiplexed readout: IQ mixer on ports 9/10, ADC on inputs 1/2
  - Ports 7,8 unused (were Q2_DL_HF / ext_flux in sample config)

Q3 and Q4 drives use SSBModulatorChannel (single OPX output + external LO), defined in
quam_config/my_quam.py. Q2 retains the standard IQ drive channel.
"""

########################################################################################################################
# %%                                             Import section
########################################################################################################################
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import json
from qualang_tools.units import unit
from quam_config import Quam, SSBModulatorChannel
from quam_builder.builder.superconducting.pulses import add_DragCosine_pulses
from quam.components.pulses import GaussianPulse, WaveformPulse
from quam.components.channels import DigitalOutputChannel
import numpy as np
from pprint import pprint

########################################################################################################################
# %%                                 QUAM loading and auxiliary functions
########################################################################################################################
machine = Quam.load()
u = unit(coerce_to_integer=True)

########################################################################################################################
# %%                                    Resonator parameters
########################################################################################################################
# All 3 resonators share a single multiplexed readout line through one external IQ mixer.
# LO from sample_config_black.py: lo_res = 6.982 GHz.
# Update rr_freq with calibrated resonator frequencies from your chip.
rr_LO = 7.3 * u.GHz
rr_freq = np.array([7.64425, 7.57402, 7.50618]) * u.GHz  # res_2, res_3, res_4
rr_if = rr_freq - rr_LO
assert np.all(np.abs(rr_if) < 400 * u.MHz), "The resonator intermediate frequency must be within [-400; 400] MHz."

# Readout amplitude split across multiplexed resonators (OPX output voltage, -0.5 to +0.5 V)
rr_amplitude = 0.5 / len(machine.qubits)

for k, qubit in enumerate(machine.qubits.values()):
    qubit.resonator.f_01 = rr_freq.tolist()[k]
    qubit.resonator.RF_frequency = qubit.resonator.f_01
    qubit.resonator.frequency_converter_up.LO_frequency = rr_LO

########################################################################################################################
# %%                                    Qubit drive parameters
########################################################################################################################
# Drive line configuration (from sample_config_black.py):
#   Q2 — IQ mixer  at lo = 4.2 GHz, ports 3/4  (both I and Q connected)
#   Q3 — SSB modulator at lo = 3.9 GHz, port 5  (single output)
#   Q4 — SSB modulator at lo = 3.9 GHz, port 9  (shared with readout)
# Update xy_freq with calibrated qubit transition frequencies from your chip.
xy_freq = np.array([4.07853, 3.996171, 3.939281]) * u.GHz  # Q2, Q3, Q4 |g>->|e>
xy_LO = np.array([4.2, 3.9, 3.9]) * u.GHz
xy_if = xy_freq - xy_LO
assert np.all(np.abs(xy_if) < 400 * u.MHz), "The xy intermediate frequency must be within [-400; 400] MHz."

# Transmon anharmonicity (to be updated after calibration)
anharmonicity = np.array([-145, 0, 0]) * u.MHz
# Drive amplitude (to be calibrated via Rabi oscillations)
xy_amplitude = 0.3

for k, qubit in enumerate(machine.qubits.values()):
    qubit.f_01 = xy_freq.tolist()[k]
    qubit.xy.RF_frequency = qubit.f_01
    qubit.xy.frequency_converter_up.LO_frequency = xy_LO.tolist()[k]
    qubit.grid_location = f"{k},0"

########################################################################################################################
# %%                                    Port configuration
########################################################################################################################
# Analog input gain (from sample_config_black.py: gain_db=20 on both ADC inputs)
machine.ports.analog_inputs["con1"][1].gain_db = 0
machine.ports.analog_inputs["con1"][2].gain_db = 0

# DC offsets on analog output ports (calibrated to null LO leakage).
# Ports 1,2 are coupler flux lines — their offset sets the coupler idle operating point.
# Ports 3,4 / 5 / 9,10 are IQ mixer / SSB modulator outputs.
port_offsets = {
    1: -0.012, 2: 0.0024, 3: -0.02405, 4: 0.002,
    5: -0.04, 9: 0.074, 10: -0.06,
}
for port_id, offset in port_offsets.items():
    machine.ports.analog_outputs["con1"][port_id].offset = offset

########################################################################################################################
# %%                             Digital outputs — RF switch control
########################################################################################################################
# Readout and Q4 drive share OPX ports 9,10.  Physical RF path selection is
# handled by external switches controlled via 3 OPX digital outputs:
#   Digital 1 — switch_readout   (enables readout mixer path)
#   Digital 2 — switch_mod       (enables SSB modulator path)
#   Digital 3 — switch_qubit     (enables qubit SSB drive path)
#
# Readout elements require switch_readout + switch_mod (delay=160 ns, buffer=0).
# Q4 drive (QC in sample config) does NOT use digital switches — its SSB modulator
# at lo_mod is on a separate RF path that is always connected.
# SquareReadoutPulse already has digital_marker="ON", so switches trigger automatically.
for qubit in machine.qubits.values():
    qubit.resonator.digital_outputs = {
        "switch_readout": DigitalOutputChannel(
            opx_output=("con1", 1), delay=160, buffer=0
        ),
        "switch_mod": DigitalOutputChannel(
            opx_output=("con1", 2), delay=160, buffer=0
        ),
    }

########################################################################################################################
# %%                                        Pulse parameters
########################################################################################################################
# Available pulse types:
# from quam.components.pulses import (
#     SquarePulse, DragGaussianPulse, DragCosinePulse,
#     FlatTopGaussianPulse, WaveformPulse, SquareReadoutPulse,
# )

for k, q in enumerate(machine.qubits):
    # Readout pulse (4 us matches sample_config_black.py readout_4us pattern)
    machine.qubits[q].resonator.operations["readout"].length = 2 * u.us
    machine.qubits[q].resonator.operations["readout"].amplitude = rr_amplitude
    # Qubit saturation pulse (long, high-power pulse for spectroscopy)
    machine.qubits[q].xy.operations["saturation"].length = 10 * u.us
    machine.qubits[q].xy.operations["saturation"].amplitude = 0.005
    if isinstance(machine.qubits[q].xy, SSBModulatorChannel):
        machine.qubits[q].xy.operations["saturation"].axis_angle = None
    # Single qubit gates
    if isinstance(machine.qubits[q].xy, SSBModulatorChannel):
        # SSB channels only support single-channel waveforms — use Gaussian.
        # Remove any stale IQ pulse operations/references from previous runs.
        ops = machine.qubits[q].xy.operations
        for key in [k for k in ops if k != "saturation"]:
            ops.pop(key)
        ops["x180"] = GaussianPulse(
            length=40, amplitude=xy_amplitude, sigma=8,
        )
        ops["x90"] = GaussianPulse(
            length=40, amplitude=xy_amplitude / 2, sigma=8,
        )
    else:
        # IQ channels support DragCosine (x180, x90, -x90, y180, y90, -y90)
        add_DragCosine_pulses(
            machine.qubits[q],
            amplitude=xy_amplitude,
            length=40,
            anharmonicity=anharmonicity.tolist()[k],
            alpha=0.0,
            detuning=0,
        )

########################################################################################################################
# %%                                  Mixer corrections
########################################################################################################################
machine.mixers["mixer2_q2.xy"].mixer.correction_gain = -0.105
machine.mixers["mixer2_q2.xy"].mixer.correction_phase = -0.085
machine.mixers["mixer1_q2.rr"].mixer.correction_gain = -0.028
machine.mixers["mixer1_q2.rr"].mixer.correction_phase = 1.59
machine.mixers["mixer1_q3.rr"].mixer.correction_gain = -0.035
machine.mixers["mixer1_q3.rr"].mixer.correction_phase = 1.6
machine.mixers["mixer1_q4.rr"].mixer.correction_gain = -0.034
machine.mixers["mixer1_q4.rr"].mixer.correction_phase = 1.623

########################################################################################################################
# %%                                  Coupler arbitrary waveform pulse
########################################################################################################################
# Placeholder waveform — replace with calibrated samples for your CZ / iSWAP gate.
# Length is derived automatically from the number of samples (1 sample = 1 ns at 1 GS/s).
coupler_waveform_samples = [0.0, 0.05, 0.1, 0.15, 0.1, 0.05, 0.0]

for pair_name in machine.active_qubit_pair_names:
    pair = machine.qubit_pairs[pair_name]
    pair.coupler.operations["arb_pulse"] = WaveformPulse(
        waveform_I=coupler_waveform_samples,
    )

########################################################################################################################
# %%                                         Save the updated QUAM
########################################################################################################################
machine.save()
pprint(machine.generate_config())
with open("qua_config.json", "w+") as f:
    json.dump(machine.generate_config(), f, indent=4)
