"""
Populate the QUAM generated by wiring_murch.py with initial values derived from sample_config_black.py.
Must be run after wiring_murch.py and prior to the first experiment.

System (physical wiring matches sample_config_black.py):
  - 3 fixed-frequency transmons (Q1, Q2, Q3) in a linear chain
  - 2 tunable couplers (C12 on port 1, C23 on port 2) with flux lines
  - Q1 drive: IQ mixer on ports 3/4 (Q1_DL)
  - Q2 drive: SSB modulator on ports 5/6 (Q2_DL; only port 5 connected)
  - Q3 drive: SSB modulator on ports 9/10 (shared with readout, time-multiplexed)
  - Multiplexed readout: IQ mixer on ports 9/10, ADC on inputs 1/2
  - Ports 7,8 unused (were Q2_DL_HF / ext_flux in sample config)

Note: The wirer models all drives as IQ pairs (it does not support singleInput).
Q2 and Q3 have IQ structure in the QUAM but physically only the I port is connected
to the SSB modulator. For SSB drives, set the mixer correction to identity (no correction).
"""

########################################################################################################################
# %%                                             Import section
########################################################################################################################
import json
from qualang_tools.units import unit
from quam_config import Quam
from quam_builder.builder.superconducting.pulses import add_DragCosine_pulses
from quam.components.pulses import GaussianPulse
from quam.components.channels import DigitalOutputChannel
import numpy as np
from pprint import pprint

########################################################################################################################
# %%                                 QUAM loading and auxiliary functions
########################################################################################################################
machine = Quam.load()
u = unit(coerce_to_integer=True)

########################################################################################################################
# %%                                    Resonator parameters
########################################################################################################################
# All 3 resonators share a single multiplexed readout line through one external IQ mixer.
# LO from sample_config_black.py: lo_res = 6.982 GHz.
# Update rr_freq with calibrated resonator frequencies from your chip.
rr_LO = 6.982 * u.GHz
rr_freq = np.array([6.850, 6.920, 7.050]) * u.GHz  # Placeholder: res_1, res_2, res_3
rr_if = rr_freq - rr_LO
assert np.all(np.abs(rr_if) < 400 * u.MHz), "The resonator intermediate frequency must be within [-400; 400] MHz."

# Readout amplitude split across multiplexed resonators (OPX output voltage, -0.5 to +0.5 V)
rr_amplitude = 0.125 / len(machine.qubits)

for k, qubit in enumerate(machine.qubits.values()):
    qubit.resonator.f_01 = rr_freq.tolist()[k]
    qubit.resonator.RF_frequency = qubit.resonator.f_01
    qubit.resonator.frequency_converter_up.LO_frequency = rr_LO

########################################################################################################################
# %%                                    Qubit drive parameters
########################################################################################################################
# Drive line configuration (from sample_config_black.py):
#   Q1 — IQ mixer  at lo_qubit = 4.241 GHz, ports 3/4  (both I and Q connected)
#   Q2 — SSB modulator at lo_qubit = 4.241 GHz, ports 5/6  (only port 5 connected)
#   Q3 — SSB modulator at lo_mod  = 5.347 GHz, ports 9/10 (shared with readout)
# Update xy_freq with calibrated qubit transition frequencies from your chip.
xy_freq = np.array([4.400, 4.500, 5.500]) * u.GHz  # Placeholder: Q1, Q2, Q3 |g>->|e>
xy_LO = np.array([4.241, 4.241, 5.347]) * u.GHz
xy_if = xy_freq - xy_LO
assert np.all(np.abs(xy_if) < 400 * u.MHz), "The xy intermediate frequency must be within [-400; 400] MHz."

# Transmon anharmonicity (typical ~-200 MHz, to be updated after calibration)
anharmonicity = np.array([-200, -200, -200]) * u.MHz
# Drive amplitude (to be calibrated via Rabi oscillations)
xy_amplitude = 0.1

for k, qubit in enumerate(machine.qubits.values()):
    qubit.f_01 = xy_freq.tolist()[k]
    qubit.xy.RF_frequency = qubit.f_01
    qubit.xy.frequency_converter_up.LO_frequency = xy_LO.tolist()[k]
    qubit.grid_location = f"{k},0"

########################################################################################################################
# %%                                    Port configuration
########################################################################################################################
# Analog input gain (from sample_config_black.py: gain_db=20 on both ADC inputs)
machine.ports.analog_inputs["con1"][1].gain_db = 20
machine.ports.analog_inputs["con1"][2].gain_db = 20

# DC offsets on analog output ports (start at 0.0 V; calibrate to null LO leakage).
# Ports 1,2 are coupler flux lines — their offset sets the coupler idle operating point.
# Ports 3,4 / 5,6 / 9,10 are IQ mixer / SSB modulator outputs.
for port_id in [1, 2, 3, 4, 5, 6, 9, 10]:
    machine.ports.analog_outputs["con1"][port_id].offset = 0.0

########################################################################################################################
# %%                             Digital outputs — RF switch control
########################################################################################################################
# Readout and Q3 drive share OPX ports 9,10.  Physical RF path selection is
# handled by external switches controlled via 3 OPX digital outputs:
#   Digital 1 — switch_readout   (enables readout mixer path)
#   Digital 2 — switch_mod       (enables SSB modulator path)
#   Digital 3 — switch_qubit     (enables qubit SSB drive path)
#
# Readout elements require switch_readout + switch_mod (delay=160 ns, buffer=0).
# Q3 drive (QC in sample config) does NOT use digital switches — its SSB modulator
# at lo_mod is on a separate RF path that is always connected.
# SquareReadoutPulse already has digital_marker="ON", so switches trigger automatically.
for qubit in machine.qubits.values():
    qubit.resonator.digital_outputs = {
        "switch_readout": DigitalOutputChannel(
            opx_output=("con1", 1), delay=160, buffer=0
        ),
        "switch_mod": DigitalOutputChannel(
            opx_output=("con1", 2), delay=160, buffer=0
        ),
    }

########################################################################################################################
# %%                                        Pulse parameters
########################################################################################################################
# Available pulse types:
# from quam.components.pulses import (
#     SquarePulse, DragGaussianPulse, DragCosinePulse,
#     FlatTopGaussianPulse, WaveformPulse, SquareReadoutPulse,
# )

for k, q in enumerate(machine.qubits):
    # Readout pulse (4 us matches sample_config_black.py readout_4us pattern)
    machine.qubits[q].resonator.operations["readout"].length = 4 * u.us
    machine.qubits[q].resonator.operations["readout"].amplitude = rr_amplitude
    # Qubit saturation pulse (long, high-power pulse for spectroscopy)
    machine.qubits[q].xy.operations["saturation"].length = 20 * u.us
    machine.qubits[q].xy.operations["saturation"].amplitude = 0.3
    # Single qubit gates — DragCosine (x180, x90, -x90, y180, y90, -y90)
    add_DragCosine_pulses(
        machine.qubits[q],
        amplitude=xy_amplitude,
        length=40,
        anharmonicity=anharmonicity.tolist()[k],
        alpha=0.0,
        detuning=0,
    )

########################################################################################################################
# %%                                         Save the updated QUAM
########################################################################################################################
machine.save()
pprint(machine.generate_config())
with open("qua_config.json", "w+") as f:
    json.dump(machine.generate_config(), f, indent=4)
